# Generated by Django 3.2.5 on 2021-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majong_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseShuffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerShuffle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('round_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoundScoreShuffle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is1', models.IntegerField()),
                ('is2', models.IntegerField()),
                ('is3', models.IntegerField()),
                ('is4', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='score',
            name='round',
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
