# Generated by Django 3.2.5 on 2021-08-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majong_processor', '0002_auto_20210801_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundscore',
            old_name='round_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='roundscore',
            old_name='score_1',
            new_name='is1',
        ),
        migrations.RenameField(
            model_name='roundscore',
            old_name='score_2',
            new_name='is2',
        ),
        migrations.RenameField(
            model_name='roundscore',
            old_name='score_3',
            new_name='is3',
        ),
        migrations.RenameField(
            model_name='roundscore',
            old_name='score_4',
            new_name='is4',
        ),
    ]
